# ⚙️ Result monad

This container wraps a result computation value into __Ok__ or when the function call failed, returns
__Err(exception)__

## 💻 API reference

::: fateful.monad.result